services:
  frontend:
    container_name: open-meteo-fe-dev
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3000"
    environment:
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true # create-ui-app >= 5.x
      FAST_REFRESH: false
      WDS_SOCKET_PORT: 3002 # The mapped port on your host machine
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true